In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = df=pd.read_csv('C:\winequality_red.csv')
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [3]:
df.quality.value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [4]:
df['quality_binary']=pd.cut(df['quality'],bins=[2.9,6.5,9], labels=['bad','good'])

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
enc = LabelEncoder()
df.quality_binary = enc.fit_transform(df.quality_binary)

In [8]:
df.quality_binary.value_counts()

0    1382
1     217
Name: quality_binary, dtype: int64

In [15]:
y=df.quality_binary
x=df.drop(['quality_binary','quality'],axis=1)

In [9]:
from sklearn.preprocessing import MinMaxScaler

In [10]:
scaler = MinMaxScaler()

In [16]:
x_scaled=pd.DataFrame((scaler.fit_transform(x)),columns=x.columns)
x_scaled

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0          0.247788          0.397260         0.00        0.068493   0.106845   
1          0.283186          0.520548         0.00        0.116438   0.143573   
2          0.283186          0.438356         0.04        0.095890   0.133556   
3          0.584071          0.109589         0.56        0.068493   0.105175   
4          0.247788          0.397260         0.00        0.068493   0.106845   
...             ...               ...          ...             ...        ...   
1594       0.141593          0.328767         0.08        0.075342   0.130217   
1595       0.115044          0.294521         0.10        0.089041   0.083472   
1596       0.150442          0.267123         0.13        0.095890   0.106845   
1597       0.115044          0.359589         0.12        0.075342   0.105175   
1598       0.123894          0.130137         0.47        0.184932   0.091820   

      free sulfur dioxide  total sulfur dioxide   density        pH  \
0                0.140845              0.098940  0.567548  0.606299   
1                0.338028              0.215548  0.494126  0.362205   
2                0.197183              0.169611  0.508811  0.409449   
3                0.225352              0.190813  0.582232  0.330709   
4                0.140845              0.098940  0.567548  0.606299   
...                   ...                   ...       ...       ...   
1594             0.436620              0.134276  0.354626  0.559055   
1595             0.535211              0.159011  0.370778  0.614173   
1596             0.394366              0.120141  0.416300  0.535433   
1597             0.436620              0.134276  0.396476  0.653543   
1598             0.239437              0.127208  0.397944  0.511811   

      sulphates   alcohol  
0      0.137725  0.153846  
1      0.209581  0.215385  
2      0.191617  0.215385  
3      0.149701  0.215385  
4      0.137725  0.153846  
...         ...       ...  
1594   0.149701  0.323077  
1595   0.257485  0.430769  
1596   0.251497  0.400000  
1597   0.227545  0.276923  
1598   0.197605  0.400000  

[1599 rows x 11 columns]

In [17]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_scaled,y,random_state=0,test_size=0.2)

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn import linear_model
from sklearn import metrics

In [19]:
reg=linear_model.LogisticRegression()
reg.fit(x_train,y_train)
y_pred=reg.predict(x_test)
print("accuracy: "+ str(reg.score(x_test,y_test)*100) + "%")

accuracy: 90.3125%


In [20]:
cm = metrics.confusion_matrix(y_test, y_pred)
cm

array([[282,   8],
       [ 23,   7]], dtype=int64)

In [21]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
print("Precision:",metrics.precision_score(y_test, y_pred))
print("Recall:",metrics.recall_score(y_test, y_pred))
print("F1 Score:",metrics.f1_score(y_test, y_pred, average='weighted'))

Accuracy: 0.903125
Precision: 0.4666666666666667
Recall: 0.23333333333333334
F1 Score: 0.8882002801120447


In [22]:
from imblearn.over_sampling import SMOTE

In [23]:
smote=SMOTE()

In [24]:
x_scaled_resample, y_resample = smote.fit_resample(x_scaled, y)

In [25]:
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1=train_test_split(x_scaled_resample,y_resample,random_state=0,test_size=0.2)

In [27]:
reg1=linear_model.LogisticRegression(C=100,solver='liblinear',penalty='l1')
reg1.fit(x_train1,y_train1)
y_pred1=reg1.predict(x_test1)
print("accuracy: "+ str(reg1.score(x_test1,y_test1)*100) + "%")

accuracy: 82.09764918625679%


In [28]:
cm1 = metrics.confusion_matrix(y_test1, y_pred1)
cm1

array([[224,  63],
       [ 36, 230]], dtype=int64)

In [29]:
print("Accuracy:",metrics.accuracy_score(y_test1, y_pred1))
print("Precision:",metrics.precision_score(y_test1, y_pred1))
print("Recall:",metrics.recall_score(y_test1, y_pred1))
print("F1 Score:",metrics.f1_score(y_test1, y_pred1, average='weighted'))

Accuracy: 0.8209764918625678
Precision: 0.7849829351535836
Recall: 0.8646616541353384
F1 Score: 0.820881644350465


In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [31]:
model = RandomForestClassifier(random_state=1)
model.fit(x_train1, y_train1)
y_pred2 = model.predict(x_test1)

print("Accuracy Score:",accuracy_score(y_test1,y_pred2))

Accuracy Score: 0.9493670886075949


In [32]:
cm2 = metrics.confusion_matrix(y_test1, y_pred2)
cm2

array([[262,  25],
       [  3, 263]], dtype=int64)

In [33]:
print("Accuracy:",metrics.accuracy_score(y_test1, y_pred2))
print("Precision:",metrics.precision_score(y_test1, y_pred2))
print("Recall:",metrics.recall_score(y_test1, y_pred2))
print("F1 Score:",metrics.f1_score(y_test1, y_pred2, average='weighted'))

Accuracy: 0.9493670886075949
Precision: 0.9131944444444444
Recall: 0.9887218045112782
F1 Score: 0.9493634460473916
